### ISSUE TITLE
NPE in crd.go:99

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#809]
```
time="2020-11-02T23:39:27Z" level=error msg="Error running check: ssl-handshake-kubernetesdefault in namespace kuberhealthy: failed to verify uuid match 6732d32b-0342-48dd-829a-42a3b63669e8 after 9 tries"
time="2020-11-02T23:39:27Z" level=debug msg="Forming new workload struct with workload type: KHCheck"
time="2020-11-02T23:39:27Z" level=error msg="could not find Kuberhealthy check with name ssl-handshake-kubernetesdefault"
time="2020-11-02T23:39:27Z" level=error msg="Error when setting execution error on check ssl-handshake-kubernetesdefault kuberhealthy could not find Kuberhealthy check with name ssl-handshake-kubernetesdefault"
time="2020-11-02T23:39:27Z" level=debug msg="Forming new workload struct with workload type: KHCheck"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x12ffddb]
goroutine 5103309 [running]:
main.getCheckState(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/build/cmd/kuberhealthy/crd.go:99 +0xbb
main.(*Kuberhealthy).setCheckExecutionError(0xc00057c230, 0xc000a9aca0, 0x1f, 0xc000a81350, 0xc, 0x17271a0, 0xc00015bd40)
	/build/cmd/kuberhealthy/kuberhealthy.go:102 +0x29b
main.(*Kuberhealthy).runCheck(0xc00057c230, 0x175a440, 0xc000c9ba40, 0x1766280, 0xc000126f00)
	/build/cmd/kuberhealthy/kuberhealthy.go:993 +0x5fb
created by main.(*Kuberhealthy).StartChecks
	/build/cmd/kuberhealthy/kuberhealthy.go:747 +0x266
```

**Comment by integrii** [comment]
![Uploading image.png…]()

**Comment by integrii** [comment]
![image](https://user-images.githubusercontent.com/98695/106684345-23be7800-657b-11eb-9ac5-bda14836318b.png)
